#!/usr/bin/env bash

# Changes the audio output for pulseaudio

current=`pactl get-default-sink`

if [[ "$current" == "alsa_output.usb-Kingston_HyperX_7.1_Audio_00000000-00.analog-stereo" ]]; then
	pactl set-default-sink alsa_output.pci-0000_00_1f.3.analog-stereo
	echo "images/icons/speaker.svg"
else
	pactl set-default-sink alsa_output.usb-Kingston_HyperX_7.1_Audio_00000000-00.analog-stereo
	echo "images/icons/headphones.svg"
fi
